## Numpy array and basics

In [1]:
import numpy as np

### Creating Array from List

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


###  List vs Numpy

In [3]:
py_list = [1, 2, 3]

print("Python List Multiplication: ", py_list * 2)

np_array = np.array([1, 2, 3]) # element wise multiplication
print("Python array multiplication: ", np_array * 2)

import time
start = time.time()
py_list = [i* 2 for i in range(1000000)]
print("\n list Operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Array Operation time: ", time.time() - start)

Python List Multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 list Operation time:  0.04597949981689453

 Array Operation time:  0.002630472183227539


### Creating Array from Scratch

In [4]:
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2,2),7)
print("Full Constant array: \n", full)

random = np.random.random((2,3))
print("Random array: \n", random)

sequence = np.arange(0, 11, 2)
print("Sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Constant array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.07634437 0.48413496 0.3311546 ]
 [0.06596549 0.42668036 0.79194216]]
Sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [5]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6],[7,8]]])

print("Tensor: ", tensor)
print("Shape: ", tensor.shape)
print("Dimension: ", tensor.ndim)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape:  (2, 2, 2)
Dimension:  3


### Array Properties

In [6]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int32


### Array Reshaping

In [7]:
arr = np.arange(12)
print("original array: ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array: \n", reshaped)

flattened = reshaped.flatten()
print("\n flattened array: \n", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array: \n", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array : \n", transpose)

original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
