# Numpy Array Operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("With Step: ", arr[1:8:2])
print("Negative Indexing: ", arr[-3])


Basic Slicing:  [3 4 5 6 7]
With Step:  [2 4 6 8]
Negative Indexing:  8


In [3]:
arr_2d = np.array([[1,2,3],[4,5,6],[7, 8, 9]])
print("Original 2D array: \n", arr_2d)
print("Specific Element: ", arr_2d[1,2])
print("Entire row: ", arr_2d[1])
print ("Entire Column: ", arr_2d[:, 1])

Original 2D array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element:  6
Entire row:  [4 5 6]
Entire Column:  [2 5 8]


# Sorting

In [4]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("\nUnsorted 2D array: \n", arr_2d_unsorted)
print("\nSorted 2D array by column:\n", np.sort(arr_2d_unsorted, axis=0))
print("\nSorted 2D array by row:\n", np.sort(arr_2d_unsorted, axis=1))

Sorted Array:  [1 1 2 3 4 5 6 9]

Unsorted 2D array: 
 [[3 1]
 [1 2]
 [2 3]]

Sorted 2D array by column:
 [[1 1]
 [2 2]
 [3 3]]

Sorted 2D array by row:
 [[1 3]
 [1 2]
 [2 3]]


## Filter

In [5]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print('Even Numbers: \n', even_number)

Even Numbers: 
 [ 2  4  6  8 10]


## Filter with Mask

In [6]:
mask = numbers > 5
print("numbers greater than 5: ", numbers[mask])

numbers greater than 5:  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [7]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP Where: ",numbers[where_result] )

[1 3 5]
(array([5, 6, 7, 8, 9], dtype=int64),)
NP Where:  [ 6  7  8  9 10]


In [8]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


## Adding and removing Data

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = arr1 + arr2
print(combined)

combined = np.concatenate((arr1, arr2))
print(combined)

[5 7 9]
[1 2 3 4 5 6]


## Array Compatibility

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility Shapes: ", a.shape == b.shape)


Compatibility Shapes:  True


In [11]:
Original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((Original, new_row))
print("Original: \n", Original)
print("\n With New Row : \n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((Original, new_col))
print("\nWith new Column: \n", with_new_col)

Original: 
 [[1 2]
 [3 4]]

 With New Row : 
 [[1 2]
 [3 4]
 [5 6]]

With new Column: 
 [[1 2 7]
 [3 4 8]]


In [12]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ",deleted)

Array after deletion:  [1 2 4 5]
